services:
  #  =================================================================
  #  Keycloak 
  #  =================================================================
  keycloak-postgres-db:
    image: postgres:18-alpine
    container_name: tea4life-keycloak-postgres-db-container
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - tea4life-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: tea4life-keycloak-container
    command: start-dev --import-realm
    depends_on:
      - keycloak-postgres-db
      - kafka
    ports:
      - "9000:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes:z
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres-db:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
      # Keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_THEME_CACHE_ANYWHERE: false
      KC_THEME_CACHE_THEMES: false
    networks:
      - tea4life-network

  #  =================================================================
  #  Kafka Apache
  #  =================================================================
  kafka:
    image: apache/kafka:latest
    container_name: tea4life-kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: 'INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:19092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - tea4life-network

  #  =================================================================
  #  Redis
  #  =================================================================
  redis:
    image: redis
    container_name: tea4life-redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_db_data:/data
    networks:
      - tea4life-network

  #  =================================================================
  #  Storage Service
  #  =================================================================  
  storage-service:
    image: huynhducphu2502/tea4life-storage-service:latest
    container_name: tea4life-storage-service-container
    ports:
      - "8081:8080"
    environment:
      # AWS S3
      - STORAGE_SERVICE_S3_ACCESS_KEY=${STORAGE_SERVICE_S3_ACCESS_KEY}
      - STORAGE_SERVICE_S3_SECRET_KEY=${STORAGE_SERVICE_S3_SECRET_KEY}
      - STORAGE_SERVICE_S3_REGION=${STORAGE_SERVICE_S3_REGION}
      - STORAGE_SERVICE_S3_BUCKET_NAME=${STORAGE_SERVICE_S3_BUCKET_NAME}
      # Kafka
      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID=${STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID}
      # CORS
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    networks:
      - tea4life-network


volumes:
  keycloak_db_data:
  redis_db_data:

networks:
  tea4life-network:
    driver: bridge