services:
  #  =================================================================
  #  Kafka Apache [Priority Order 1]
  #  =================================================================
  kafka:
    image: apache/kafka:latest
    container_name: tea4life-kafka-container
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: 'INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:19092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - tea4life-network

  #  =================================================================
  #  Postgres Database [Priority Order 1]
  #  =================================================================
  keycloak-postgres-db:
    image: postgres:18-alpine
    container_name: tea4life-keycloak-postgres-db-container
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - tea4life-network

  #  =================================================================
  #  Redis [Priority Order 1]
  #  =================================================================
  redis:
    image: redis:latest
    container_name: tea4life-redis-container
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_db_data:/data
    networks:
      - tea4life-network

  #  =================================================================
  #  Keycloak [Priority Order 2]
  #  =================================================================
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: tea4life-keycloak-container
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "/opt/keycloak/bin/kc.sh build --health-enabled=true &&
       /opt/keycloak/bin/kc.sh start-dev --import-realm"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes:z
    healthcheck:
      test: [ "CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready | echo $?" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      keycloak-postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9000:8080"
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres-db:5432/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
      # Keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_HEALTH_PORT: 9000
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    networks:
      - tea4life-network

  #  =================================================================
  #  Discovery Server [Priority Order 3]
  #  =================================================================
  discovery-server:
    image: huynhducphu2502/tea4life-discovery-server:latest
    container_name: tea4life-discovery-server-container
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1" ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8761:8761"
    networks:
      - tea4life-network
  
  #  =================================================================
  #  Storage Service [Priority Order 4]
  #  =================================================================  
  storage-service:
    image: huynhducphu2502/tea4life-storage-service:latest
    container_name: tea4life-storage-service-container
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1" ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8081:8080"
    environment:
      # AWS S3
      - STORAGE_SERVICE_S3_ACCESS_KEY=${STORAGE_SERVICE_S3_ACCESS_KEY}
      - STORAGE_SERVICE_S3_SECRET_KEY=${STORAGE_SERVICE_S3_SECRET_KEY}
      - STORAGE_SERVICE_S3_REGION=${STORAGE_SERVICE_S3_REGION}
      - STORAGE_SERVICE_S3_BUCKET_NAME=${STORAGE_SERVICE_S3_BUCKET_NAME}
      # Kafka
      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}
      - STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID=${STORAGE_SERVICE_KAFKA_CONSUMER_GROUP_ID}
      # Discovery Server
      - EUREKA_SERVICE_URL=${EUREKA_SERVICE_URL}
    networks:
      - tea4life-network

  #  =================================================================
  #  Gateway Server [Priority Order 5]
  #  =================================================================
  gateway-server:
    image: huynhducphu2502/tea4life-gateway-server:latest
    container_name: tea4life-gateway-server-container
    depends_on:
      storage-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1" ]
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    ports:
      - "8888:8888"
    environment:
      # Keycloak
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_JWT_SET_URI=${KEYCLOAK_JWT_SET_URI}
      # CORS
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      # Discovery Server
      - EUREKA_SERVICE_URL=${EUREKA_SERVICE_URL}
    networks:
      - tea4life-network


volumes:
  keycloak_db_data:
  redis_db_data:

networks:
  tea4life-network:
    driver: bridge