services:
  #  =================================================================
  #  Keycloak Infrastructure
  #  =================================================================
  keycloak-postgres-db:
    image: postgres:18-alpine
    container_name: keycloak-postgres-db-container
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - tea4life-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak-container
    command: start-dev --import-realm
    depends_on:
      - keycloak-postgres-db
      - broker
    ports:
      - "9000:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
      - ./providers:/opt/keycloak/providers
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin123
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    networks:
      - tea4life-network

  #  =================================================================
  #  Kafka Apache
  #  =================================================================
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092" 
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: 'INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:19092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - tea4life-network 

volumes:
  keycloak_db_data:

networks:
  tea4life-network:
    driver: bridge